jobs:
  ubuntu-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v7
      - name: node
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install
        run: |
          npm install
          node_modules/.bin/vsce package
      - env:
          VSCE_PAT: ${{ secrets.PUB_TOKEN }}
        if: contains(github.event.head_commit.message, '[publish]')
        name: Publish
        run: |
          node_modules/.bin/vsce publish
      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: vscode-plugin
          path: '*.vsix'
name: Develop
'on':
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
